apiVersion: v1
kind: Service
metadata:
  name: betting-api
  namespace: {{ include "betting-system.namespace" . }}
  labels:
    app: betting-api
    {{- include "betting-system.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: betting-api
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.service.port }}
    protocol: TCP
    name: http
