apiVersion: v1
kind: Secret
metadata:
  name: {{ include "betting-system.fullname" . }}-secrets
  namespace: {{ include "betting-system.namespace" . }}
  labels:
    {{- include "betting-system.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
