apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: betting-system-ingress
  namespace: betting-system
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - dev.betting-system.com
    secretName: betting-system-tls-dev
  rules:
  - host: dev.betting-system.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: betting-api
            port:
              number: 8000
