apiVersion: apps/v1
kind: Deployment
metadata:
  name: betting-api
  namespace: betting-system
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: betting-frontend
  namespace: betting-system
spec:
  replicas: 1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: betting-api-hpa
  namespace: betting-system
spec:
  minReplicas: 1
  maxReplicas: 3
